import os
import glob

# ================= 配置区 =================
# 您的数据集根目录 (请确保与 generate_correction_dataset.py 的输出目录一致)
DATA_ROOT = "correction_datasets_double_res_0" 
# 输出的配置文件名
OUTPUT_FILE = "Datasets/processed_datasets/dataset_config.py"

def get_core_name(dataset_name):
    """
    提取数据集的核心名称用于比对。
    新增了对 qb_ 前缀的处理。
    """
    name = dataset_name.lower().strip()
    # 移除前缀
    if name.startswith("ge_"):
        name = name[3:]
    elif name.startswith("lotsa_"):
        name = name[6:]
    elif name.startswith("qb_"):
        name = name[3:]
        
    # 移除后缀
    suffixes = ['_correction_data', '_train', '_test', '_val', '_valid', '.pkl']
    for suffix in suffixes:
        if name.endswith(suffix):
            name = name[:-len(suffix)]
    return name

def generate_config():
    print(f"🔍 正在扫描数据目录: {DATA_ROOT} ...")
    
    if not os.path.exists(DATA_ROOT):
        print(f"❌ 错误: 未找到目录 {DATA_ROOT}，请检查路径配置。")
        return

    # 1. 使用递归模式搜索所有 _correction_data.pkl 文件，不再依赖特定的模型文件夹名
    search_pattern = os.path.join(DATA_ROOT, "**", "*_correction_data.pkl")
    pkl_files = glob.glob(search_pattern, recursive=True)
    
    if not pkl_files:
        print(f"❌ 错误: 在 {DATA_ROOT} 及其子目录下未找到任何 pkl 文件。")
        print("   请确保您已经运行了 generate_correction_dataset 脚本并成功生成了数据。")
        return

    # 2. 提取并去重所有数据集名称 (因为不同模型可能处理了相同的数据集)
    all_datasets_set = set()
    for f in pkl_files:
        filename = os.path.basename(f)
        clean_name = filename.replace("_correction_data.pkl", "")
        all_datasets_set.add(clean_name)
    
    all_datasets = list(all_datasets_set)
    print(f"📦 共发现 {len(all_datasets)} 个独立数据集。")

    # 3. 分类与去重
    qb_list = []
    qb_min_list = []   # 新增: 用于存放分钟级 QB 数据
    qb_hour_list = []  # 新增: 用于存放小时级 QB 数据
    
    ge_list = []
    lotsa_all_list = []
    
    # 3.1 初步分类
    for name in all_datasets:
        if name.startswith("QB_"):
            qb_list.append(name)
            # 细分 QB 数据集
            if "_min_" in name.lower():
                qb_min_list.append(name)
            elif "_hour_" in name.lower():
                qb_hour_list.append(name)
        elif name.startswith("GE_"):
            ge_list.append(name)
        else:
            # 假定其余为 LOTSA 等训练集
            lotsa_all_list.append(name)
            
    # 3.2 提取所有测试集 (GE + QB) 的核心指纹，用于过滤训练集，防止数据泄露
    test_cores = set([get_core_name(n) for n in qb_list + ge_list])
    
    lotsa_clean_list = []
    duplicates = []
    
    # 3.3 筛选 Clean LOTSA
    for name in lotsa_all_list:
        core = get_core_name(name)
        if core in test_cores:
            duplicates.append(name)
        else:
            lotsa_clean_list.append(name)
            
    # 排序以保持稳定
    qb_list.sort()
    qb_min_list.sort()
    qb_hour_list.sort()
    ge_list.sort()
    lotsa_all_list.sort()
    lotsa_clean_list.sort()
    
    print(f"📊 统计结果:")
    print(f"   🔹 QuitoBench All (Test): {len(qb_list)}")
    print(f"      ├─ Min-level: {len(qb_min_list)}")
    print(f"      └─ Hour-level: {len(qb_hour_list)}")
    print(f"   🔹 Gift_Eval (Test): {len(ge_list)}")
    print(f"   🔹 LOTSA All (Train Raw): {len(lotsa_all_list)}")
    print(f"   ⚠️ 发现与基准测试重合/泄露的训练集: {len(duplicates)}")
    if len(duplicates) > 0:
        print(f"      (示例: {duplicates[:3]}...)")
    print(f"   ✅ LOTSA Clean (Train Final): {len(lotsa_clean_list)}")

    # 4. 生成 Python 代码内容
    content = f'''# Auto-generated by generate_config.py
# 包含了 QuitoBench、Gift_Eval 测试集和经过清洗(去除重合)的 LOTSA 训练集

# ==========================================
# 1. QuitoBench Datasets (Test)
# ==========================================
QB_Univariate_Datasets = [
    {_format_list(qb_list)}
]

QB_Min_Datasets = [
    {_format_list(qb_min_list)}
]

QB_Hour_Datasets = [
    {_format_list(qb_hour_list)}
]

# ==========================================
# 2. Gift Eval Datasets (Test)
# ==========================================
GE_Univariate_Datasets = [
    {_format_list(ge_list)}
]

# ==========================================
# 3. LOTSA Datasets (Train - Cleaned)
# 剔除了与 QuitoBench 和 Gift Eval 重合的部分
# ==========================================
LOTSA_Train_Clean_Datasets = [
    {_format_list(lotsa_clean_list)}
]

# ==========================================
# 4. LOTSA Datasets (Train - All)
# 包含所有原始 LOTSA 数据
# ==========================================
LOTSA_Train_All_Datasets = [
    {_format_list(lotsa_all_list)}
]

# ==========================================
# 5. Dataset Groups Dictionary
# ==========================================
DATASET_GROUPS = {{
    "qb_test_all": QB_Univariate_Datasets,
    "qb_test_min": QB_Min_Datasets,
    "qb_test_hour": QB_Hour_Datasets,
    "ge_test_all": GE_Univariate_Datasets,
    "lotsa_train_clean": LOTSA_Train_Clean_Datasets,
    "lotsa_train_all": LOTSA_Train_All_Datasets
}}
'''

    # 5. 写入文件
    output_dir = os.path.dirname(OUTPUT_FILE)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)
        
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"\n💾 配置文件已生成: {OUTPUT_FILE}")

def _format_list(lst):
    """辅助函数：格式化列表为 Python 代码字符串"""
    if not lst:
        return ""
    return ",\n    ".join([f'"{x}"' for x in lst])

if __name__ == "__main__":
    generate_config()